"""Qt compatibility layer for PySide6/PySide2."""

from __future__ import annotations

try:
    from PySide6.QtCore import QObject, QThread, Signal, Qt, QTimer, QSize
    from PySide6.QtGui import QIcon
    from PySide6.QtWidgets import (
        QApplication,
        QCheckBox,
        QComboBox,
        QFileDialog,
        QFrame,
        QFormLayout,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QTextBrowser,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QScrollArea,
        QSlider,
        QStackedWidget,
        QTabWidget,
        QTableWidget,
        QTableWidgetItem,
        QToolButton,
        QVBoxLayout,
        QWidget,
    )
except Exception:
    from PySide2.QtCore import QObject, QThread, Signal, Qt, QTimer, QSize
    from PySide2.QtGui import QIcon
    from PySide2.QtWidgets import (
        QApplication,
        QCheckBox,
        QComboBox,
        QFileDialog,
        QFrame,
        QFormLayout,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QTextBrowser,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QScrollArea,
        QSlider,
        QStackedWidget,
        QTabWidget,
        QTableWidget,
        QTableWidgetItem,
        QToolButton,
        QVBoxLayout,
        QWidget,
    )

__all__ = [
    "QApplication",
    "QCheckBox",
    "QComboBox",
    "QFileDialog",
    "QFrame",
    "QFormLayout",
    "QGroupBox",
    "QHBoxLayout",
    "QHeaderView",
    "QIcon",
    "QInputDialog",
    "QLabel",
    "QLineEdit",
    "QListWidget",
    "QMessageBox",
    "QObject",
    "QProgressBar",
    "QPushButton",
    "QScrollArea",
    "QSlider",
    "QSize",
    "QStackedWidget",
    "QTabWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QTextBrowser",
    "QThread",
    "QToolButton",
    "Qt",
    "QTimer",
    "QVBoxLayout",
    "QWidget",
    "Signal",
]
